module.exports = {
    booleanType: 0,
    smallStringType: 1,
    stringType: 2,
    largeStringType: 3,
    nanoNumberType: 4,
    smallNumberType: 5,
    numberType: 6,
    floatType: 7,
    doubleType: 8,
    smallArrayType: 9,
    arrayType: 10,
    largeArrayType: 11,
    objectType: 12,
    objectKey: 13,
};
